lang = "Rust"
organization_id = "ginger-society"
dir = "."
spec_url = "/openapi.json"

[services."@ginger-society/tekton-sidekick"]
prod = "https://tekton.gingersociety.org/sidekick"
stage = "https://tekton.gingersociety.org/sidekick"

[services."@ginger-society/IAMService"]
stage = "https://api.gingersociety.org/iam"
prod = "https://api.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"
prod_k8 = "http://iam-service-api-service/iam"

[services."@ginger-society/ginger-gitter"]
stage = "https://source.gingersociety.org"
prod = "https://source.gingersociety.org"

[services."@ginger-society/MetadataService"]
stage = "https://api.gingersociety.org/metadata"
prod = "https://api.gingersociety.org/metadata"

[portals_refs]

[ws_refs."@ginger-society/MetadataService"]
prod = ""
stage = ""

[ws_refs."@ginger-society/ginger-gitter"]
stage = ""
prod = ""

[ws_refs."@ginger-society/IAMService"]
stage = ""
stage_k8 = ""
prod_k8 = ""
prod = ""

[ws_refs."@ginger-society/tekton-sidekick"]
prod = ""
stage = ""

[urls]

[urls_ws]
